### ISSUE TITLE
Add Ability to Filter by Additional Variables

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#5] opened 2016-04-14 18:44 UTC

**Comment by jwildfire** [comment] 2016-06-03 18:16
Not sure what this one means. @brittsikora to clarify or close.

**Comment by brittsikora** [comment] 2016-06-03 20:29
Found in the original issue: Add the ability to sort by other variables such as gender, site, dose, etc.

**Comment by jwildfire** [comment] 2016-06-05 03:52
duplicate of https://github.com/RhoInc/safety-outlier-explorer/issues/8

**Closed by jwildfire** 2016-06-05 03:52 UTC
